title: 同行陌路两不疑
subtitle: 同行陌路-- 两不疑
description: 只有迎风，风筝才能飞得更高。
keywords:
author: 同行陌路-- 两不疑
language: zh-CN
timezone: ''

# URL
url: https://blog.138gl.com/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  app_id: 7HZ261W96L
  api_key: cb702f6ec26558e81b1f650f2e793b28
  index_name: hexo
twitter: hexojs
github: hexojs/hexo
